version: "3.7"

services:
  application:
    container_name: mediathekviewweb
    #image: mediathekview/mediathekviewweb:latest
    build: .
    restart: always
    depends_on:
      - elasticsearch
      - redis
    environment:
      DATA_DIRECTORY: /data
      WEBSERVER_PORT: 8000
      INDEX: 'true'
      WORKER_COUNT:
      WORKER_ARGS:
      REDIS_HOST: redis
      REDIS_PORT:
      REDIS_PASSWORD:
      REDIS_DB:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      MATOMO_ENABLED:
      MATOMO_URL:
      MATOMO_SITE_URL:
      MATOMO_AUTH_TOKEN:
      MATOMO_SITE_ID:
      CONTACT_NAME:
      CONTACT_STREET:
      CONTACT_POSTCODE:
      CONTACT_CITY:
      CONTACT_MAIL:
      ARIA_ENABLED: 'true'
      ARIA_HOST: 'aria2'
      ARIA_PORT: 6800
      ARIA_PATH: '/jsonrpc'
      ARIA_SECRET: 'someobvioussecret'
      ARIA_SECURE: 'false'
    volumes:
      - "mediathekviewweb:/data"
    ports:
      - "8000:8000"
    networks:
      - aria
      - elasticsearch
      - redis

  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.14"
    restart: always
    environment:
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    networks:
      - elasticsearch

  redis:
    container_name: redis
    image: "redis:6-alpine"
    restart: always
    volumes:
      - "redis:/data"
    networks:
      - redis

  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=someobvioussecret
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Europe/Berlin
    volumes:
      - ./aria2-config:/config
      - ./aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#    network_mode: host
#    network_mode: bridge
    networks:
      - aria
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

volumes:
  mediathekviewweb:
  redis:
  elasticsearch:

networks:
  elasticsearch:
  redis:
  aria: